services:
  redis:
    image: redis:7.2
    container_name: redis
    ports:
      - '6380:6379'
    networks:
      - bendis_seller
    volumes:
      - redis_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5

  seller_service:
    restart: always
    container_name: seller
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: Seller
    ports:
      - '5452:5432'
    volumes:
      - SellerData:/var/lib/postgresql/data
    networks:
      - bendis_seller
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "root" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  redis_data: {}
  UserData: {}
  SellerData: {}
networks:
  bendis_seller:
    driver: bridge
