spring:
  application:
    name: seller-service

  datasource:
    second:
      url: jdbc:postgresql://localhost:5451/Product
      username: root
      password: root
    third:
      url: jdbc:postgresql://localhost:5455/Order
      username: root
      password: root
    fourth:
      url: jdbc:postgresql://localhost:5456/Seller
      username: root
      password: root
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  data:
    redis:
      host: redis
      port: 6379

cloudinary:
  cloud:
    name: dddwkgrcy
  api:
    key: 668583881613156
    secret: 7jymaVAgMxu5Pc50toz0YvwJ2ro