spring:
  application:
    name: seller-service

  datasource:
    first:
      url: jdbc:postgresql://localhost:5450/User
      username: root
      password: root
    second:
      url: jdbc:postgresql://localhost:5451/Product
      username: root
      password: root
    third:
      url: jdbc:postgresql://localhost:5452/Order
      username: root
      password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  data:
    redis:
      host: redis
      port: 6379
